# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np
from PyQt5.QtGui import QPixmap
import logo_rc

class Ui_Form(object):
    def read(self):
        global df1,model_amp,model_phase,freq
        content = self.comboBox.currentText()
        if  content =="RT5870":
            self.lineEdit.setText('2.33')
            self.lineEdit_2.setText('0.8')
            Er=2.33
            H=0.8
        elif content =="RO4835": 
            self.lineEdit.setText('3.48')
            self.lineEdit_2.setText('1.54')
            Er=3.48
            H=1.54
        elif content =="RO4730G3": 
            self.lineEdit.setText('3')
            self.lineEdit_2.setText('0.52')
            Er=3
            H=0.52
        elif content =="RO4003C": 
            self.lineEdit.setText('3.38')
            self.lineEdit_2.setText('0.41')
            Er=3.38
            H=0.41
        elif content =="RO6002": 
            self.lineEdit.setText('2.94')
            self.lineEdit_2.setText('0.76')
            Er=2.94
            H=0.76
        elif content =="RT5880C": 
            self.lineEdit.setText('2.2')
            self.lineEdit_2.setText('0.79')
            Er=2.2
            H=0.79
        elif content =="FR4": 
            self.lineEdit.setText('4.7')
            self.lineEdit_2.setText('0.4')
            Er=4.7
            H=0.4
        else :
            Er=float(self.lineEdit.text())
            H=float(self.lineEdit_2.text())
        #Er,H=self.combos()
        Nv=int(self.lineEdit_3.text())
        W=float(self.lineEdit_4.text())
        freq1=float(self.lineEdit_5.text())
        freq2=float(self.lineEdit_6.text())
        freq=np.arange(freq1,freq2,0.01)
        Er=np.full(len(freq),Er)
        Nv=3.5*np.full(len(freq),Nv)
        W=np.full(len(freq),W)
        H=np.full(len(freq),H)
        data=[H,Er,Nv,W,freq]
        df = pd.DataFrame(data=data)
        df1=df.T
        df1= df1.values
        df1=df1.reshape(df1.shape[0], df1.shape[1], 1)
        model_amp=load_model(r'C:\Users\user\Desktop\courses\Deep learning\app\lstml3_70.h5',compile=False)
        model_phase=load_model(r'C:\Users\user\Desktop\courses\Deep learning\app\LSTM_phase_50epoch.h5',compile=False)

        return df1
    def Predict(self):
        y=model_amp.predict(df1)
        self.graphicsView.plot(freq,y[:,0])
        self.graphicsView.showGrid(x=True, y=True)
        self.graphicsView_2.plot(freq,y[:,1])
        self.graphicsView_2.showGrid(x=True, y=True)
        k=model_phase.predict(df1)
        self.graphicsView_3.plot(freq,k[:,0])
        self.graphicsView_3.showGrid(x=True, y=True)
        self.graphicsView_4.plot(freq,k[:,1])
        self.graphicsView_4.showGrid(x=True, y=True)

    def clear(self): 
        self.graphicsView.clear()
        self.graphicsView_2.clear()
        self.graphicsView_3.clear()
        self.graphicsView_4.clear()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1055, 769)
        Form.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"background-color: rgb(197, 227, 255);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(1655, 692))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 47, 46, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 111, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 176, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 305, 16, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 369, 44, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 85, 133, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 150, 133, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 214, 133, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 279, 133, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 23, 82, 18))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 343, 133, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 434, 48, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 408, 133, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 500, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 472, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 470, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(450, 460, 291, 191))
        self.label_8.setObjectName("label_8")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(311, 21, 520, 392))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView = PlotWidget(self.widget)
        self.graphicsView.setMaximumSize(QtCore.QSize(256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.graphicsView_2 = PlotWidget(self.widget)
        self.graphicsView_2.setMaximumSize(QtCore.QSize(256, 192))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_2.addWidget(self.graphicsView_2, 0, 1, 1, 1)
        self.graphicsView_3 = PlotWidget(self.widget)
        self.graphicsView_3.setMaximumSize(QtCore.QSize(256, 192))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayout_2.addWidget(self.graphicsView_3, 1, 0, 1, 1)
        self.graphicsView_4 = PlotWidget(self.widget)
        self.graphicsView_4.setMaximumSize(QtCore.QSize(256, 192))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout_2.addWidget(self.graphicsView_4, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton_2.clicked.connect(self.clear)
        self.pushButton.clicked.connect(self.read)
        self.pushButton_3.clicked.connect(self.Predict)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PCB Type"))
        self.label_2.setText(_translate("Form", "Er"))
        self.label_3.setText(_translate("Form", "H"))
        self.label_4.setText(_translate("Form", "Nv"))
        self.label_5.setText(_translate("Form", "W"))
        self.label_6.setText(_translate("Form", "Freq_min"))
        self.comboBox.setItemText(0, _translate("Form", "RT5870"))
        self.comboBox.setItemText(1, _translate("Form", "RO4835 "))
        self.comboBox.setItemText(2, _translate("Form", "RO4730G3"))
        self.comboBox.setItemText(3, _translate("Form", "RO4003C"))
        self.comboBox.setItemText(4, _translate("Form", "RO6002"))
        self.comboBox.setItemText(5, _translate("Form", "RT5880C"))
        self.comboBox.setItemText(6, _translate("Form", "FR4"))
        self.comboBox.setItemText(7, _translate("Form", "other"))
        self.label_7.setText(_translate("Form", "Freq_max"))
        self.pushButton_2.setText(_translate("Form", "Clear"))
        self.pushButton.setText(_translate("Form", "Submit"))
        self.pushButton_3.setText(_translate("Form", "Predict"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/SIW.PNG\"/></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
